### ISSUE TITLE
建议选一款好看的书法字体作为默认字体

### ISSUE THREAD

**Issue by fanqielin** [janghood/shuimo-ui#30]
“这个项目的艺术成分很高的。”
“有多高？”
“三四层楼那么高。”
太正统的字体感觉和UI不协调，建议能弄精选一种书法字体做默认或有配置项，这样艺术成分就更上一层楼了

**Comment by higuaifan** [comment]
感谢您的建议，
书法字体符合整体风格的大多是有商业版权的，本身使用微软雅黑和苹方并不突兀，
我个人建议可以使用 字魂的 [武林江湖体](https://izihun.com/shangyongziti/644.html)，但并不能作为我们这个项目推荐的字体。

**Comment by wanghaisheng** [comment]
@higuaifan  假如我要用一款字体，是要全局替换 font family吗 然后重新编译安装？没法在install 基础上通过代码加载字体吗
  font-family: PingFang SC, Microsoft YaHei;

比如这个 
https://github.com/chawyehsu/lxgw-wenkai-webfont

**Comment by higuaifan** [comment]
@wanghaisheng 在`playground`场景下，你可以直接在`/playground/src/assets/index.css`中
``` css
@import 'lxgw-wenkai-webfont/style.css';

body {
  font-family: "LXGW WenKai";
}

/* Mono font (optional) */
pre, code, textarea {
  font-family: "LXGW WenKai Mono";
}

```

你可以看到下面有个`Mono font (optional)`，
在[lxgw-wenkai-webfont](https://github.com/chawyehsu/lxgw-wenkai-webfont)的`demo`中也是提到了的，`pre,code`额外指定了`mono`字体，此处我们需要在他的`demo`的基础上添加`textarea`。
这是因为`textarea`需要确保输入的文字以等宽字体显示，方便对齐和排版。

测试效果如下：
![image](https://github.com/shuimo-design/shuimo-ui/assets/9988024/b6303c24-2826-4ed1-a733-b6ac48132627)


关于`textarea`的等宽字体相关的知识，
你可以参考：
[Why <textarea> and <textfield> not taking font-family and font-size from body?](https://stackoverflow.com/questions/2874813/why-textarea-and-textfield-not-taking-font-family-and-font-size-from-body)
